n = input('Digite algo: ')
print(f'o tipo primitivo desse valor é {type(n)}')
print(f'é alfabético? {n.isalpha()}')
print(f'é alfanúmerico? {n.isalnum()}')
print(f'é decimal? {n.isdecimal()}')
print(f'está em minusculo? {n.islower()}')
print(f'é um número? {n.isnumeric()}')
print(f'está em maiuscula? {n.isupper()}')
print(f'só tem espaços? {n.isspace()}')
print(f'está capitalizada? {n.istitle()}')